import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

export const sendVerificationEmail = async (to: string, token: string) => {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.EMAIL_USER, // Your Gmail address
      pass: process.env.EMAIL_PASS, // App Password generated by Google
    },
  });

  const mailOptions = {
    from: process.env.EMAIL_USER,
    to,
    subject: "Verify Your Email",
    text: `Please click the following link to verify your email: 
  ${process.env.FRONTEND_DOMAIN}/api/users/verify-email?token=${token}`,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log("Verification email sent successfully");
  } catch (err) {
    console.error("Error sending verification email", err);
    throw err;
  }
};

